//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Helper;

namespace KiiniHelp.ServiceTicket {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceTicket.IServiceTicket")]
    public interface IServiceTicket {
        
        [OperationContract(Action="http://tempuri.org/IServiceTicket/Guardar", ReplyAction="http://tempuri.org/IServiceTicket/GuardarResponse")]
        void Guardar(int idUsuario, int idArbol, List<HelperCampoMascaraCaptura> lstCaptura);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTicketChannel : IServiceTicket, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTicketClient : ClientBase<IServiceTicket>, IServiceTicket {
        
        public ServiceTicketClient() {
        }
        
        public ServiceTicketClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTicketClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTicketClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTicketClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Guardar(int idUsuario, int idArbol, List<HelperCampoMascaraCaptura> lstCaptura) {
            base.Channel.Guardar(idUsuario, idArbol, lstCaptura);
        }
    }
}
