//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceEncuesta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEncuesta.IServiceEncuesta")]
    public interface IServiceEncuesta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestas", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestaById", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestaByIdResponse")]
        KiiniNet.Entities.Cat.Usuario.Encuesta ObtenerEncuestaById(int idEncuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestaByIdTicket", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestaByIdTicketResponse")]
        KiiniNet.Entities.Cat.Usuario.Encuesta ObtenerEncuestaByIdTicket(int idTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/GuardarEncuesta", ReplyAction="http://tempuri.org/IServiceEncuesta/GuardarEncuestaResponse")]
        void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/Consulta", ReplyAction="http://tempuri.org/IServiceEncuesta/ConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> Consulta(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/HabilitarEncuesta", ReplyAction="http://tempuri.org/IServiceEncuesta/HabilitarEncuestaResponse")]
        void HabilitarEncuesta(int idencuesta, bool habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestasPendientesUsuario", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestasPendientesUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperEncuesta> ObtenerEncuestasPendientesUsuario(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEncuestaChannel : KiiniHelp.ServiceEncuesta.IServiceEncuesta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEncuestaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceEncuesta.IServiceEncuesta>, KiiniHelp.ServiceEncuesta.IServiceEncuesta {
        
        public ServiceEncuestaClient() {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion) {
            return base.Channel.ObtenerEncuestas(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Usuario.Encuesta ObtenerEncuestaById(int idEncuesta) {
            return base.Channel.ObtenerEncuestaById(idEncuesta);
        }
        
        public KiiniNet.Entities.Cat.Usuario.Encuesta ObtenerEncuestaByIdTicket(int idTicket) {
            return base.Channel.ObtenerEncuestaByIdTicket(idTicket);
        }
        
        public void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta) {
            base.Channel.GuardarEncuesta(encuesta);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> Consulta(string descripcion) {
            return base.Channel.Consulta(descripcion);
        }
        
        public void HabilitarEncuesta(int idencuesta, bool habilitado) {
            base.Channel.HabilitarEncuesta(idencuesta, habilitado);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperEncuesta> ObtenerEncuestasPendientesUsuario(int idUsuario) {
            return base.Channel.ObtenerEncuestasPendientesUsuario(idUsuario);
        }
    }
}
