//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Usuario;

namespace KiiniHelp.ServiceEncuesta {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceEncuesta.IServiceEncuesta")]
    public interface IServiceEncuesta {
        
        [OperationContract(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestas", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestasResponse")]
        List<Encuesta> ObtenerEncuestas(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceEncuesta/GuardarEncuesta", ReplyAction="http://tempuri.org/IServiceEncuesta/GuardarEncuestaResponse")]
        void GuardarEncuesta(Encuesta encuesta);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEncuestaChannel : IServiceEncuesta, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEncuestaClient : ClientBase<IServiceEncuesta>, IServiceEncuesta {
        
        public ServiceEncuestaClient() {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<Encuesta> ObtenerEncuestas(bool insertarSeleccion) {
            return base.Channel.ObtenerEncuestas(insertarSeleccion);
        }
        
        public void GuardarEncuesta(Encuesta encuesta) {
            base.Channel.GuardarEncuesta(encuesta);
        }
    }
}
