//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceEncuesta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEncuesta.IServiceEncuesta")]
    public interface IServiceEncuesta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/ObtenerEncuestas", ReplyAction="http://tempuri.org/IServiceEncuesta/ObtenerEncuestasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/GuardarEncuesta", ReplyAction="http://tempuri.org/IServiceEncuesta/GuardarEncuestaResponse")]
        void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/Consulta", ReplyAction="http://tempuri.org/IServiceEncuesta/ConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> Consulta(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEncuesta/HabilitarEncuesta", ReplyAction="http://tempuri.org/IServiceEncuesta/HabilitarEncuestaResponse")]
        void HabilitarEncuesta(int idencuesta, bool habilitado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEncuestaChannel : KiiniHelp.ServiceEncuesta.IServiceEncuesta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEncuestaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceEncuesta.IServiceEncuesta>, KiiniHelp.ServiceEncuesta.IServiceEncuesta {
        
        public ServiceEncuestaClient() {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEncuestaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion) {
            return base.Channel.ObtenerEncuestas(insertarSeleccion);
        }
        
        public void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta) {
            base.Channel.GuardarEncuesta(encuesta);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> Consulta(string descripcion) {
            return base.Channel.Consulta(descripcion);
        }
        
        public void HabilitarEncuesta(int idencuesta, bool habilitado) {
            base.Channel.HabilitarEncuesta(idencuesta, habilitado);
        }
    }
}
