//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Mascaras;

namespace KiiniHelp.ServiceMascaraAcceso {
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BusinessMascaras.CatalogoGenerico", Namespace="http://schemas.datacontract.org/2004/07/KinniNet.Core.Operacion")]
    [Serializable()]
    public partial class BusinessMascarasCatalogoGenerico : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string DescripcionField;
        
        [OptionalField()]
        private int IdField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceMascaraAcceso.IServiceMascaras")]
    public interface IServiceMascaras {
        
        [OperationContract(Action="http://tempuri.org/IServiceMascaras/CrearMascara", ReplyAction="http://tempuri.org/IServiceMascaras/CrearMascaraResponse")]
        void CrearMascara(Mascara mascara);
        
        [OperationContract(Action="http://tempuri.org/IServiceMascaras/ObtenerMascaraCaptura", ReplyAction="http://tempuri.org/IServiceMascaras/ObtenerMascaraCapturaResponse")]
        Mascara ObtenerMascaraCaptura(int idMascara);
        
        [OperationContract(Action="http://tempuri.org/IServiceMascaras/ObtenerMascarasAcceso", ReplyAction="http://tempuri.org/IServiceMascaras/ObtenerMascarasAccesoResponse")]
        List<Mascara> ObtenerMascarasAcceso(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceMascaras/ObtenerCatalogoCampoMascara", ReplyAction="http://tempuri.org/IServiceMascaras/ObtenerCatalogoCampoMascaraResponse")]
        List<BusinessMascarasCatalogoGenerico> ObtenerCatalogoCampoMascara(string tabla);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMascarasChannel : IServiceMascaras, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMascarasClient : ClientBase<IServiceMascaras>, IServiceMascaras {
        
        public ServiceMascarasClient() {
        }
        
        public ServiceMascarasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMascarasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMascarasClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMascarasClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearMascara(Mascara mascara) {
            base.Channel.CrearMascara(mascara);
        }
        
        public Mascara ObtenerMascaraCaptura(int idMascara) {
            return base.Channel.ObtenerMascaraCaptura(idMascara);
        }
        
        public List<Mascara> ObtenerMascarasAcceso(bool insertarSeleccion) {
            return base.Channel.ObtenerMascarasAcceso(insertarSeleccion);
        }
        
        public List<BusinessMascarasCatalogoGenerico> ObtenerCatalogoCampoMascara(string tabla) {
            return base.Channel.ObtenerCatalogoCampoMascara(tabla);
        }
    }
}
