//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Arbol.Ubicaciones.Domicilio;

namespace KiiniHelp.ServiceSistemaDomicilio {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaDomicilio.IServiceDomicilioSistema")]
    public interface IServiceDomicilioSistema {
        
        [OperationContract(Action="http://tempuri.org/IServiceDomicilioSistema/ObtenerColoniasCp", ReplyAction="http://tempuri.org/IServiceDomicilioSistema/ObtenerColoniasCpResponse")]
        List<Colonia> ObtenerColoniasCp(int cp, bool insertarSeleccion);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDomicilioSistemaChannel : IServiceDomicilioSistema, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDomicilioSistemaClient : ClientBase<IServiceDomicilioSistema>, IServiceDomicilioSistema {
        
        public ServiceDomicilioSistemaClient() {
        }
        
        public ServiceDomicilioSistemaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDomicilioSistemaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDomicilioSistemaClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDomicilioSistemaClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<Colonia> ObtenerColoniasCp(int cp, bool insertarSeleccion) {
            return base.Channel.ObtenerColoniasCp(cp, insertarSeleccion);
        }
    }
}
