//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceDiasHorario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDiasHorario.IServiceDiasHorario")]
    public interface IServiceDiasHorario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioDefault", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioDefaultResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioDefault(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioConsulta", ReplyAction="http://tempuri.org/IServiceDiasHorario/ObtenerHorarioConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioConsulta(System.Nullable<int> idGrupoSolicito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/CrearHorario", ReplyAction="http://tempuri.org/IServiceDiasHorario/CrearHorarioResponse")]
        void CrearHorario(KiiniNet.Entities.Cat.Usuario.Horario horario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDiasHorario/Habilitar", ReplyAction="http://tempuri.org/IServiceDiasHorario/HabilitarResponse")]
        void Habilitar(int idHorario, bool habilitado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDiasHorarioChannel : KiiniHelp.ServiceDiasHorario.IServiceDiasHorario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDiasHorarioClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceDiasHorario.IServiceDiasHorario>, KiiniHelp.ServiceDiasHorario.IServiceDiasHorario {
        
        public ServiceDiasHorarioClient() {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDiasHorarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDiasHorarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioDefault(bool insertarSeleccion) {
            return base.Channel.ObtenerHorarioDefault(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Horario> ObtenerHorarioConsulta(System.Nullable<int> idGrupoSolicito) {
            return base.Channel.ObtenerHorarioConsulta(idGrupoSolicito);
        }
        
        public void CrearHorario(KiiniNet.Entities.Cat.Usuario.Horario horario) {
            base.Channel.CrearHorario(horario);
        }
        
        public void Habilitar(int idHorario, bool habilitado) {
            base.Channel.Habilitar(idHorario, habilitado);
        }
    }
}
