//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Usuario;
using KiiniNet.Entities.Helper;

namespace KiiniHelp.ServiceSubGrupoUsuario {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSubGrupoUsuario.IServiceSubGrupoUsuario")]
    public interface IServiceSubGrupoUsuario {
        
        [OperationContract(Action="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuario", ReplyAction="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGruposUsuarioResponse")]
        List<HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGrupoUsuario", ReplyAction="http://tempuri.org/IServiceSubGrupoUsuario/ObtenerSubGrupoUsuarioResponse")]
        SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idSubRol);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSubGrupoUsuarioChannel : IServiceSubGrupoUsuario, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSubGrupoUsuarioClient : ClientBase<IServiceSubGrupoUsuario>, IServiceSubGrupoUsuario {
        
        public ServiceSubGrupoUsuarioClient() {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubGrupoUsuarioClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubGrupoUsuarioClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerSubGruposUsuario(idGrupoUsuario, insertarSeleccion);
        }
        
        public SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idSubRol) {
            return base.Channel.ObtenerSubGrupoUsuario(idGrupoUsuario, idSubRol);
        }
    }
}
