//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.UserControls.Consultas {
    
    
    public partial class UcConsultaUsuarios {
        
        /// <summary>
        /// rptUsuarios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptUsuarios;
        
        /// <summary>
        /// UcDetalleUsuario1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KiiniHelp.UserControls.Detalles.UcDetalleUsuario UcDetalleUsuario1;
    }
}
