//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Sistema;
using KiiniNet.Entities.Operacion.Usuarios;

namespace KiiniHelp.ServiceSeguridad {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSeguridad.IServiceSecurity")]
    public interface IServiceSecurity {
        
        [OperationContract(Action="http://tempuri.org/IServiceSecurity/Autenticate", ReplyAction="http://tempuri.org/IServiceSecurity/AutenticateResponse")]
        bool Autenticate(string user, string password);
        
        [OperationContract(Action="http://tempuri.org/IServiceSecurity/GetUserDataAutenticate", ReplyAction="http://tempuri.org/IServiceSecurity/GetUserDataAutenticateResponse")]
        Usuario GetUserDataAutenticate(string user, string password);
        
        [OperationContract(Action="http://tempuri.org/IServiceSecurity/ObtenerMenuUsuario", ReplyAction="http://tempuri.org/IServiceSecurity/ObtenerMenuUsuarioResponse")]
        List<Menu> ObtenerMenuUsuario(int idUsuario, int idArea, bool arboles);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSecurityChannel : IServiceSecurity, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSecurityClient : ClientBase<IServiceSecurity>, IServiceSecurity {
        
        public ServiceSecurityClient() {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSecurityClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Autenticate(string user, string password) {
            return base.Channel.Autenticate(user, password);
        }
        
        public Usuario GetUserDataAutenticate(string user, string password) {
            return base.Channel.GetUserDataAutenticate(user, password);
        }
        
        public List<Menu> ObtenerMenuUsuario(int idUsuario, int idArea, bool arboles) {
            return base.Channel.ObtenerMenuUsuario(idUsuario, idArea, arboles);
        }
    }
}
