//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaCatalogos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaCatalogos.IServiceCatalogos")]
    public interface IServiceCatalogos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/CrearCatalogo", ReplyAction="http://tempuri.org/IServiceCatalogos/CrearCatalogoResponse")]
        void CrearCatalogo(string nombreCatalogo, bool esMascara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ObtenerCatalogo", ReplyAction="http://tempuri.org/IServiceCatalogos/ObtenerCatalogoResponse")]
        KiiniNet.Entities.Cat.Sistema.Catalogos ObtenerCatalogo(int idCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ObtenerCatalogos", ReplyAction="http://tempuri.org/IServiceCatalogos/ObtenerCatalogosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogos(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ObtenerCatalogoConsulta", ReplyAction="http://tempuri.org/IServiceCatalogos/ObtenerCatalogoConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogoConsulta(System.Nullable<int> idCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ObtenerCatalogosMascaraCaptura", ReplyAction="http://tempuri.org/IServiceCatalogos/ObtenerCatalogosMascaraCapturaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogosMascaraCaptura(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/Habilitar", ReplyAction="http://tempuri.org/IServiceCatalogos/HabilitarResponse")]
        void Habilitar(int idCatalogo, bool habilitado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/AgregarRegistro", ReplyAction="http://tempuri.org/IServiceCatalogos/AgregarRegistroResponse")]
        void AgregarRegistro(int idCatalogo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ObtenerRegistrosCatalogo", ReplyAction="http://tempuri.org/IServiceCatalogos/ObtenerRegistrosCatalogoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.CatalogoGenerico> ObtenerRegistrosCatalogo(int idCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/CrearCatalogoExcel", ReplyAction="http://tempuri.org/IServiceCatalogos/CrearCatalogoExcelResponse")]
        void CrearCatalogoExcel(string nombreCatalogo, bool esMascara, string archivo, string hoja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogos/ActualizarCatalogoExcel", ReplyAction="http://tempuri.org/IServiceCatalogos/ActualizarCatalogoExcelResponse")]
        void ActualizarCatalogoExcel(int idCatalogo, bool esMascara, string archivo, string hoja);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCatalogosChannel : KiiniHelp.ServiceSistemaCatalogos.IServiceCatalogos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogosClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaCatalogos.IServiceCatalogos>, KiiniHelp.ServiceSistemaCatalogos.IServiceCatalogos {
        
        public ServiceCatalogosClient() {
        }
        
        public ServiceCatalogosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearCatalogo(string nombreCatalogo, bool esMascara) {
            base.Channel.CrearCatalogo(nombreCatalogo, esMascara);
        }
        
        public KiiniNet.Entities.Cat.Sistema.Catalogos ObtenerCatalogo(int idCatalogo) {
            return base.Channel.ObtenerCatalogo(idCatalogo);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogos(bool insertarSeleccion) {
            return base.Channel.ObtenerCatalogos(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogoConsulta(System.Nullable<int> idCatalogo) {
            return base.Channel.ObtenerCatalogoConsulta(idCatalogo);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogosMascaraCaptura(bool insertarSeleccion) {
            return base.Channel.ObtenerCatalogosMascaraCaptura(insertarSeleccion);
        }
        
        public void Habilitar(int idCatalogo, bool habilitado) {
            base.Channel.Habilitar(idCatalogo, habilitado);
        }
        
        public void AgregarRegistro(int idCatalogo, string descripcion) {
            base.Channel.AgregarRegistro(idCatalogo, descripcion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.CatalogoGenerico> ObtenerRegistrosCatalogo(int idCatalogo) {
            return base.Channel.ObtenerRegistrosCatalogo(idCatalogo);
        }
        
        public void CrearCatalogoExcel(string nombreCatalogo, bool esMascara, string archivo, string hoja) {
            base.Channel.CrearCatalogoExcel(nombreCatalogo, esMascara, archivo, hoja);
        }
        
        public void ActualizarCatalogoExcel(int idCatalogo, bool esMascara, string archivo, string hoja) {
            base.Channel.ActualizarCatalogoExcel(idCatalogo, esMascara, archivo, hoja);
        }
    }
}
