//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceInformacionConsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInformacionConsulta.IServiceInformacionConsulta")]
    public interface IServiceInformacionConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsulta", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsultaResponse" +
            "")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsulta(KinniNet.Business.Utils.BusinessVariables.EnumTiposInformacionConsulta tipoinfoConsulta, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsultaArbol", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsultaArbolRes" +
            "ponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsultaArbol(int idArbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsultaById", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/ObtenerInformacionConsultaByIdResp" +
            "onse")]
        KiiniNet.Entities.Operacion.InformacionConsulta ObtenerInformacionConsultaById(int idInformacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/GuardarInformacionConsulta", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/GuardarInformacionConsultaResponse" +
            "")]
        void GuardarInformacionConsulta(KiiniNet.Entities.Operacion.InformacionConsulta informacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/GuardarHit", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/GuardarHitResponse")]
        void GuardarHit(int idArbol, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/ObtenerConsulta", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/ObtenerConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerConsulta(System.Nullable<int> idTipoInformacionConsulta, System.Nullable<int> idTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInformacionConsulta/HabilitarInformacion", ReplyAction="http://tempuri.org/IServiceInformacionConsulta/HabilitarInformacionResponse")]
        void HabilitarInformacion(int idInformacion, bool habilitado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceInformacionConsultaChannel : KiiniHelp.ServiceInformacionConsulta.IServiceInformacionConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceInformacionConsultaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceInformacionConsulta.IServiceInformacionConsulta>, KiiniHelp.ServiceInformacionConsulta.IServiceInformacionConsulta {
        
        public ServiceInformacionConsultaClient() {
        }
        
        public ServiceInformacionConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceInformacionConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInformacionConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInformacionConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsulta(KinniNet.Business.Utils.BusinessVariables.EnumTiposInformacionConsulta tipoinfoConsulta, bool insertarSeleccion) {
            return base.Channel.ObtenerInformacionConsulta(tipoinfoConsulta, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsultaArbol(int idArbol) {
            return base.Channel.ObtenerInformacionConsultaArbol(idArbol);
        }
        
        public KiiniNet.Entities.Operacion.InformacionConsulta ObtenerInformacionConsultaById(int idInformacion) {
            return base.Channel.ObtenerInformacionConsultaById(idInformacion);
        }
        
        public void GuardarInformacionConsulta(KiiniNet.Entities.Operacion.InformacionConsulta informacion) {
            base.Channel.GuardarInformacionConsulta(informacion);
        }
        
        public void GuardarHit(int idArbol, int idUsuario) {
            base.Channel.GuardarHit(idArbol, idUsuario);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerConsulta(System.Nullable<int> idTipoInformacionConsulta, System.Nullable<int> idTipoDocumento) {
            return base.Channel.ObtenerConsulta(idTipoInformacionConsulta, idTipoDocumento);
        }
        
        public void HabilitarInformacion(int idInformacion, bool habilitado) {
            base.Channel.HabilitarInformacion(idInformacion, habilitado);
        }
    }
}
