//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Mascaras;

namespace KiiniHelp.ServiceSistemaTipoCampoMascara {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaTipoCampoMascara.IServiceTipoCampoMascara")]
    public interface IServiceTipoCampoMascara {
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoCampoMascara/ObtenerTipoCampoMascara", ReplyAction="http://tempuri.org/IServiceTipoCampoMascara/ObtenerTipoCampoMascaraResponse")]
        List<TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoCampoMascara/TipoCampoMascaraId", ReplyAction="http://tempuri.org/IServiceTipoCampoMascara/TipoCampoMascaraIdResponse")]
        TipoCampoMascara TipoCampoMascaraId(int idTipoCampo);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoCampoMascaraChannel : IServiceTipoCampoMascara, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoCampoMascaraClient : ClientBase<IServiceTipoCampoMascara>, IServiceTipoCampoMascara {
        
        public ServiceTipoCampoMascaraClient() {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoCampoMascaraClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoCampoMascaraClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoCampoMascara(insertarSeleccion);
        }
        
        public TipoCampoMascara TipoCampoMascaraId(int idTipoCampo) {
            return base.Channel.TipoCampoMascaraId(idTipoCampo);
        }
    }
}
