//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Sistema;

namespace KiiniHelp.ServiceSistemaTipoUsuario {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaTipoUsuario.IServiceTipoUsuario")]
    public interface IServiceTipoUsuario {
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoUsuario/ObtenerTiposUsuarioResidentes", ReplyAction="http://tempuri.org/IServiceTipoUsuario/ObtenerTiposUsuarioResidentesResponse")]
        List<TipoUsuario> ObtenerTiposUsuarioResidentes(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoUsuario/ObtenerTiposUsuarioInvitados", ReplyAction="http://tempuri.org/IServiceTipoUsuario/ObtenerTiposUsuarioInvitadosResponse")]
        List<TipoUsuario> ObtenerTiposUsuarioInvitados(bool insertarSeleccion);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoUsuarioChannel : IServiceTipoUsuario, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoUsuarioClient : ClientBase<IServiceTipoUsuario>, IServiceTipoUsuario {
        
        public ServiceTipoUsuarioClient() {
        }
        
        public ServiceTipoUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoUsuarioClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoUsuarioClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<TipoUsuario> ObtenerTiposUsuarioResidentes(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposUsuarioResidentes(insertarSeleccion);
        }
        
        public List<TipoUsuario> ObtenerTiposUsuarioInvitados(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposUsuarioInvitados(insertarSeleccion);
        }
    }
}
