//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Sistema;

namespace KiiniHelp.ServiceSistemaTipoDocumento {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaTipoDocumento.IServiceTipoDocumento")]
    public interface IServiceTipoDocumento {
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoDocumento/ObtenerTipoDocumentos", ReplyAction="http://tempuri.org/IServiceTipoDocumento/ObtenerTipoDocumentosResponse")]
        List<TipoDocumento> ObtenerTipoDocumentos(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoDocumento/ObtenerTiposDocumentoId", ReplyAction="http://tempuri.org/IServiceTipoDocumento/ObtenerTiposDocumentoIdResponse")]
        TipoDocumento ObtenerTiposDocumentoId(int idTipoDocumento);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoDocumentoChannel : IServiceTipoDocumento, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoDocumentoClient : ClientBase<IServiceTipoDocumento>, IServiceTipoDocumento {
        
        public ServiceTipoDocumentoClient() {
        }
        
        public ServiceTipoDocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoDocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoDocumentoClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoDocumentoClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<TipoDocumento> ObtenerTipoDocumentos(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoDocumentos(insertarSeleccion);
        }
        
        public TipoDocumento ObtenerTiposDocumentoId(int idTipoDocumento) {
            return base.Channel.ObtenerTiposDocumentoId(idTipoDocumento);
        }
    }
}
