//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceArea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceArea.IServiceArea")]
    public interface IServiceArea {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArea/ObtenerAreasUsuario", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasUsuario(int idUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArea/ObtenerAreasUsuarioPublico", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasUsuarioPublicoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasUsuarioPublico(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArea/ObtenerAreasTipoUsuario", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasTipoUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasTipoUsuario(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArea/ObtenerAreas", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreas(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArea/Guardar", ReplyAction="http://tempuri.org/IServiceArea/GuardarResponse")]
        void Guardar(KiiniNet.Entities.Operacion.Area area);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAreaChannel : KiiniHelp.ServiceArea.IServiceArea, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAreaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceArea.IServiceArea>, KiiniHelp.ServiceArea.IServiceArea {
        
        public ServiceAreaClient() {
        }
        
        public ServiceAreaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAreaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAreaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAreaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasUsuario(int idUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerAreasUsuario(idUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasUsuarioPublico(bool insertarSeleccion) {
            return base.Channel.ObtenerAreasUsuarioPublico(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreasTipoUsuario(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerAreasTipoUsuario(idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Area> ObtenerAreas(bool insertarSeleccion) {
            return base.Channel.ObtenerAreas(insertarSeleccion);
        }
        
        public void Guardar(KiiniNet.Entities.Operacion.Area area) {
            base.Channel.Guardar(area);
        }
    }
}
