//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Operacion;

namespace KiiniHelp.ServiceArea {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceArea.IServiceArea")]
    public interface IServiceArea {
        
        [OperationContract(Action="http://tempuri.org/IServiceArea/ObtenerAreasUsuario", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasUsuarioResponse")]
        List<Area> ObtenerAreasUsuario(int idUsuario);
        
        [OperationContract(Action="http://tempuri.org/IServiceArea/ObtenerAreas", ReplyAction="http://tempuri.org/IServiceArea/ObtenerAreasResponse")]
        List<Area> ObtenerAreas(bool insertarSeleccion);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAreaChannel : IServiceArea, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAreaClient : ClientBase<IServiceArea>, IServiceArea {
        
        public ServiceAreaClient() {
        }
        
        public ServiceAreaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAreaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAreaClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAreaClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<Area> ObtenerAreasUsuario(int idUsuario) {
            return base.Channel.ObtenerAreasUsuario(idUsuario);
        }
        
        public List<Area> ObtenerAreas(bool insertarSeleccion) {
            return base.Channel.ObtenerAreas(insertarSeleccion);
        }
    }
}
