//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Sistema;

namespace KiiniHelp.ServiceSistemaSubRol {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaSubRol.IServiceSubRol")]
    public interface IServiceSubRol {
        
        [OperationContract(Action="http://tempuri.org/IServiceSubRol/ObtenerSubRolesByTipoGrupo", ReplyAction="http://tempuri.org/IServiceSubRol/ObtenerSubRolesByTipoGrupoResponse")]
        List<SubRol> ObtenerSubRolesByTipoGrupo(int idTipoGrupo, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceSubRol/ObtenerSubRolById", ReplyAction="http://tempuri.org/IServiceSubRol/ObtenerSubRolByIdResponse")]
        SubRol ObtenerSubRolById(int idSubRol);
        
        [OperationContract(Action="http://tempuri.org/IServiceSubRol/ObtenerSubRolesByGrupoUsuarioRol", ReplyAction="http://tempuri.org/IServiceSubRol/ObtenerSubRolesByGrupoUsuarioRolResponse")]
        List<SubRol> ObtenerSubRolesByGrupoUsuarioRol(int idGrupoUsuario, int idRol, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceSubRol/ObtenerTipoSubRol", ReplyAction="http://tempuri.org/IServiceSubRol/ObtenerTipoSubRolResponse")]
        List<SubRol> ObtenerTipoSubRol(int idTipoGrupo, bool insertarSeleccion);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSubRolChannel : IServiceSubRol, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSubRolClient : ClientBase<IServiceSubRol>, IServiceSubRol {
        
        public ServiceSubRolClient() {
        }
        
        public ServiceSubRolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSubRolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubRolClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSubRolClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<SubRol> ObtenerSubRolesByTipoGrupo(int idTipoGrupo, bool insertarSeleccion) {
            return base.Channel.ObtenerSubRolesByTipoGrupo(idTipoGrupo, insertarSeleccion);
        }
        
        public SubRol ObtenerSubRolById(int idSubRol) {
            return base.Channel.ObtenerSubRolById(idSubRol);
        }
        
        public List<SubRol> ObtenerSubRolesByGrupoUsuarioRol(int idGrupoUsuario, int idRol, bool insertarSeleccion) {
            return base.Channel.ObtenerSubRolesByGrupoUsuarioRol(idGrupoUsuario, idRol, insertarSeleccion);
        }
        
        public List<SubRol> ObtenerTipoSubRol(int idTipoGrupo, bool insertarSeleccion) {
            return base.Channel.ObtenerTipoSubRol(idTipoGrupo, insertarSeleccion);
        }
    }
}
