//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Arbol.Nodos;
using KiiniNet.Entities.Cat.Operacion;

namespace KiiniHelp.ServiceArbolAcceso {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceArbolAcceso.IServiceArbolAcceso")]
    public interface IServiceArbolAcceso {
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel1", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel1Response")]
        List<Nivel1> ObtenerNivel1(int idTipoArbol, int idTipoUsuario, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel2", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel2Response")]
        List<Nivel2> ObtenerNivel2(int idTipoArbol, int idTipoUsuario, int idNivel1, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel3", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel3Response")]
        List<Nivel3> ObtenerNivel3(int idTipoArbol, int idTipoUsuario, int idNivel2, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel4", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel4Response")]
        List<Nivel4> ObtenerNivel4(int idTipoArbol, int idTipoUsuario, int idNivel3, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel5", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel5Response")]
        List<Nivel5> ObtenerNivel5(int idTipoArbol, int idTipoUsuario, int idNivel4, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel6", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel6Response")]
        List<Nivel6> ObtenerNivel6(int idTipoArbol, int idTipoUsuario, int idNivel5, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel7", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerNivel7Response")]
        List<Nivel7> ObtenerNivel7(int idTipoArbol, int idTipoUsuario, int idNivel6, bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/EsNodoTerminal", ReplyAction="http://tempuri.org/IServiceArbolAcceso/EsNodoTerminalResponse")]
        bool EsNodoTerminal(int idTipoUsuario, int idTipoArbol, int nivel1, Nullable<int> nivel2, Nullable<int> nivel3, Nullable<int> nivel4, Nullable<int> nivel5, Nullable<int> nivel6, Nullable<int> nivel7);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/GuardarArbol", ReplyAction="http://tempuri.org/IServiceArbolAcceso/GuardarArbolResponse")]
        void GuardarArbol(ArbolAcceso arbol);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerArblodesAccesoByGruposUsuario", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerArblodesAccesoByGruposUsuarioRespon" +
            "se")]
        List<ArbolAcceso> ObtenerArblodesAccesoByGruposUsuario(int idUsuario, int idTipoArbol, int idArea);
        
        [OperationContract(Action="http://tempuri.org/IServiceArbolAcceso/ObtenerArbolAcceso", ReplyAction="http://tempuri.org/IServiceArbolAcceso/ObtenerArbolAccesoResponse")]
        ArbolAcceso ObtenerArbolAcceso(int idArbol);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceArbolAccesoChannel : IServiceArbolAcceso, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceArbolAccesoClient : ClientBase<IServiceArbolAcceso>, IServiceArbolAcceso {
        
        public ServiceArbolAccesoClient() {
        }
        
        public ServiceArbolAccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceArbolAccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArbolAccesoClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArbolAccesoClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<Nivel1> ObtenerNivel1(int idTipoArbol, int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel1(idTipoArbol, idTipoUsuario, insertarSeleccion);
        }
        
        public List<Nivel2> ObtenerNivel2(int idTipoArbol, int idTipoUsuario, int idNivel1, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel2(idTipoArbol, idTipoUsuario, idNivel1, insertarSeleccion);
        }
        
        public List<Nivel3> ObtenerNivel3(int idTipoArbol, int idTipoUsuario, int idNivel2, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel3(idTipoArbol, idTipoUsuario, idNivel2, insertarSeleccion);
        }
        
        public List<Nivel4> ObtenerNivel4(int idTipoArbol, int idTipoUsuario, int idNivel3, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel4(idTipoArbol, idTipoUsuario, idNivel3, insertarSeleccion);
        }
        
        public List<Nivel5> ObtenerNivel5(int idTipoArbol, int idTipoUsuario, int idNivel4, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel5(idTipoArbol, idTipoUsuario, idNivel4, insertarSeleccion);
        }
        
        public List<Nivel6> ObtenerNivel6(int idTipoArbol, int idTipoUsuario, int idNivel5, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel6(idTipoArbol, idTipoUsuario, idNivel5, insertarSeleccion);
        }
        
        public List<Nivel7> ObtenerNivel7(int idTipoArbol, int idTipoUsuario, int idNivel6, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel7(idTipoArbol, idTipoUsuario, idNivel6, insertarSeleccion);
        }
        
        public bool EsNodoTerminal(int idTipoUsuario, int idTipoArbol, int nivel1, Nullable<int> nivel2, Nullable<int> nivel3, Nullable<int> nivel4, Nullable<int> nivel5, Nullable<int> nivel6, Nullable<int> nivel7) {
            return base.Channel.EsNodoTerminal(idTipoUsuario, idTipoArbol, nivel1, nivel2, nivel3, nivel4, nivel5, nivel6, nivel7);
        }
        
        public void GuardarArbol(ArbolAcceso arbol) {
            base.Channel.GuardarArbol(arbol);
        }
        
        public List<ArbolAcceso> ObtenerArblodesAccesoByGruposUsuario(int idUsuario, int idTipoArbol, int idArea) {
            return base.Channel.ObtenerArblodesAccesoByGruposUsuario(idUsuario, idTipoArbol, idArea);
        }
        
        public ArbolAcceso ObtenerArbolAcceso(int idArbol) {
            return base.Channel.ObtenerArbolAcceso(idArbol);
        }
    }
}
