//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Usuario;

namespace KiiniHelp.ServiceSla {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSla.IServiceSla")]
    public interface IServiceSla {
        
        [OperationContract(Action="http://tempuri.org/IServiceSla/ObtenerSla", ReplyAction="http://tempuri.org/IServiceSla/ObtenerSlaResponse")]
        List<SLA> ObtenerSla(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceSla/Guardar", ReplyAction="http://tempuri.org/IServiceSla/GuardarResponse")]
        void Guardar(SLA sla);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSlaChannel : IServiceSla, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSlaClient : ClientBase<IServiceSla>, IServiceSla {
        
        public ServiceSlaClient() {
        }
        
        public ServiceSlaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSlaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSlaClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSlaClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<SLA> ObtenerSla(bool insertarSeleccion) {
            return base.Channel.ObtenerSla(insertarSeleccion);
        }
        
        public void Guardar(SLA sla) {
            base.Channel.Guardar(sla);
        }
    }
}
