//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaNotificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaNotificacion.IServiceNotificacion")]
    public interface IServiceNotificacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNotificacion/ObtenerTipos", ReplyAction="http://tempuri.org/IServiceNotificacion/ObtenerTiposResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoNotificacion> ObtenerTipos(bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNotificacionChannel : KiiniHelp.ServiceSistemaNotificacion.IServiceNotificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNotificacionClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaNotificacion.IServiceNotificacion>, KiiniHelp.ServiceSistemaNotificacion.IServiceNotificacion {
        
        public ServiceNotificacionClient() {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNotificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoNotificacion> ObtenerTipos(bool insertarSeleccion) {
            return base.Channel.ObtenerTipos(insertarSeleccion);
        }
    }
}
