//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceSistemaCanal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSistemaCanal.IServiceCanal")]
    public interface IServiceCanal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCanal/ObtenerCanales", ReplyAction="http://tempuri.org/IServiceCanal/ObtenerCanalesResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Canal> ObtenerCanales(bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCanalChannel : KiiniHelp.ServiceSistemaCanal.IServiceCanal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCanalClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceSistemaCanal.IServiceCanal>, KiiniHelp.ServiceSistemaCanal.IServiceCanal {
        
        public ServiceCanalClient() {
        }
        
        public ServiceCanalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCanalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCanalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCanalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Canal> ObtenerCanales(bool insertarSeleccion) {
            return base.Channel.ObtenerCanales(insertarSeleccion);
        }
    }
}
