//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using KiiniNet.Entities.Cat.Sistema;

namespace KiiniHelp.ServiceSistemaTipoEncuesta {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceSistemaTipoEncuesta.IServiceTipoEncuesta")]
    public interface IServiceTipoEncuesta {
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoEncuesta/ObtenerTiposEncuesta", ReplyAction="http://tempuri.org/IServiceTipoEncuesta/ObtenerTiposEncuestaResponse")]
        List<TipoEncuesta> ObtenerTiposEncuesta(bool insertarSeleccion);
        
        [OperationContract(Action="http://tempuri.org/IServiceTipoEncuesta/TipoEncuestaId", ReplyAction="http://tempuri.org/IServiceTipoEncuesta/TipoEncuestaIdResponse")]
        TipoEncuesta TipoEncuestaId(int idTipoEncuesta);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTipoEncuestaChannel : IServiceTipoEncuesta, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTipoEncuestaClient : ClientBase<IServiceTipoEncuesta>, IServiceTipoEncuesta {
        
        public ServiceTipoEncuestaClient() {
        }
        
        public ServiceTipoEncuestaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTipoEncuestaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoEncuestaClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTipoEncuestaClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<TipoEncuesta> ObtenerTiposEncuesta(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposEncuesta(insertarSeleccion);
        }
        
        public TipoEncuesta TipoEncuestaId(int idTipoEncuesta) {
            return base.Channel.TipoEncuestaId(idTipoEncuesta);
        }
    }
}
